Repository nextcloud/globalsiteselector, pull requests merged in 2025-02, with the labels that each got.

#170 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#168 Add oidc support
  README.md
  lib/Controller/MasterController.php
  lib/Controller/SlaveController.php
  lib/Master.php
  lib/Slave.php
  lib/UserDiscoveryModules/ManualUserMapping.php
  lib/UserDiscoveryModules/UserDiscoveryOIDC.php
Labels: 3. to review, enhancement

#165 Add gss.updatels.interval config to tune the interval between lookup-server updates
  README.md
  lib/BackgroundJobs/UpdateLookupServer.php
Labels: feedback-requested
